package com.wst.model;

import com.wst.model.base.BaseEmailAttach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmailAttach extends BaseEmailAttach<EmailAttach> {
	public static final EmailAttach dao = new EmailAttach().dao();
}
