package com.wst.model;

import com.jfinal.plugin.activerecord.Page;
import com.wst.model.base.BaseEmail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Email extends BaseEmail<Email> {
	public static final Email dao = new Email().dao();
	/**发送人*/
	private User poster;

	public Page<Email> paginate(Integer start,Integer max,String receiveId, Integer state) {
		return paginate(start,max,"SELECT e.* "," FROM t_email e,t_user_email ue WHERE e.id = ue.email_id AND ue.receive_id = ? AND ue.state = ?", receiveId,state);
	}

	public User getPoster() {
		return poster;
	}

	public void setPoster(User poster) {
		this.poster = poster;
	}
	
}
