package com.wst.model;

import com.wst.model.base.BaseUserEmail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserEmail extends BaseUserEmail<UserEmail> {
	public static final UserEmail dao = new UserEmail().dao();
}
