package com.wst.model;

import com.wst.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	
	public User login(String userName,String passWord){
		return findFirst("select * from t_user where userName=? and password=?", userName,passWord);
	}
	
	public User getUserById(String id){
		return User.dao.findFirst("select * from t_user where id = ?", id);
	}
}
