package com.wst.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserEmail<M extends BaseUserEmail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setReceiveId(java.lang.String receiveId) {
		set("receive_id", receiveId);
		return (M)this;
	}

	public java.lang.String getReceiveId() {
		return get("receive_id");
	}

	public M setReadState(java.lang.Integer readState) {
		set("read_state", readState);
		return (M)this;
	}

	public java.lang.Integer getReadState() {
		return get("read_state");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setEmailId(java.lang.String emailId) {
		set("email_id", emailId);
		return (M)this;
	}

	public java.lang.String getEmailId() {
		return get("email_id");
	}

}
