package com.wst.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEmailAttach<M extends BaseEmailAttach<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setEmailId(java.lang.String emailId) {
		set("email_id", emailId);
		return (M)this;
	}

	public java.lang.String getEmailId() {
		return get("email_id");
	}

	public M setAttachId(java.lang.String attachId) {
		set("attach_id", attachId);
		return (M)this;
	}

	public java.lang.String getAttachId() {
		return get("attach_id");
	}

}
